//
//  UserModel.swft.swift
//  TextCrunch
//
//  Created by Derek Dowling on 2015-01-12.
//  Copyright (c) 2015 Text Crunch. All rights reserved.
//

import Foundation
import CoreLocation

class UserModel {
    var email: String
    var pass: String?
    var accountId: String
    var paymentToken: String
    
    init(email: String, pass: String?){
        self.email = email
        self.pass = pass
        self.accountId = ""//Account ID is generated by Parse upon insertion into ourbackend, so our model just initializes it to "".
        self.paymentToken = ""//Payment system is not online yet, so we just provide "" for now.
    }
    
}
